name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-pdf-converter .

    - name: Run Docker container
      run: docker run -d -p 80:80 --name file-converter my-pdf-converter .

    - name: Copy files to public directory
      run: |
        mkdir public
        docker cp file-converter:/usr/share/nginx/html public/

    - name: Stop and remove Docker container
      run: docker rm -f file-converter

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
